icu_codes = {'af': 'Afrikaans',
             'ak': 'Akan',
             'sq': 'Albanian',
             'am': 'Amharic',
             'ar': 'Arabic',
             'hy': 'Armenian',
             'as': 'Assamese',
             'az': 'Azerbaijani',
             'bm': 'Bambara',
             'eu': 'Basque',
             'be': 'Belarusian',
             'bn': 'Bengali',
             'bs': 'Bosnian',
             'br': 'Breton',
             'bg': 'Bulgarian',
             'my': 'Burmese',
             'ca': 'Catalan',
             'zh': 'Chinese',
             'kw': 'Cornish',
             'hr': 'Croatian',
             'cs': 'Czech',
             'da': 'Danish',
             'nl': 'Dutch',
             'dz': 'Dzongkha',
             'en': 'English',
             'eo': 'Esperanto',
             'et': 'Estonian',
             'ee': 'Ewe',
             'fo': 'Faroese',
             'fi': 'Finnish',
             'fr': 'French',
             'ff': 'Fulah',
             'gl': 'Galician',
             'lg': 'Ganda',
             'ka': 'Georgian',
             'de': 'German',
             'el': 'Greek',
             'gu': 'Gujarati',
             'ha': 'Hausa',
             'he': 'Hebrew',
             'hi': 'Hindi',
             'hu': 'Hungarian',
             'is': 'Icelandic',
             'ig': 'Igbo',
             'id': 'Indonesian',
             'ga': 'Irish',
             'it': 'Italian',
             'ja': 'Japanese',
             'kl': 'Kalaallisut',
             'kn': 'Kannada',
             'ks': 'Kashmiri',
             'kk': 'Kazakh',
             'km': 'Khmer',
             'ki': 'Kikuyu',
             'rw': 'Kinyarwanda',
             'ko': 'Korean',
             'ky': 'Kyrgyz',
             'lo': 'Lao',
             'lv': 'Latvian',
             'ln': 'Lingala',
             'lt': 'Lithuanian',
             'lu': 'Luba-Katanga',
             'lb': 'Luxembourgish',
             'mk': 'Macedonian',
             'mg': 'Malagasy',
             'ms': 'Malay',
             'ml': 'Malayalam',
             'mt': 'Maltese',
             'gv': 'Manx',
             'mr': 'Marathi',
             'mn': 'Mongolian',
             'ne': 'Nepali',
             'nd': 'North Ndebele',
             'se': 'Northern Sami',
             'no': 'Norwegian',
             'nb': 'Norwegian Bokmål',
             'nn': 'Norwegian Nynorsk',
             'or': 'Oriya',
             'om': 'Oromo',
             'os': 'Ossetic',
             'ps': 'Pashto',
             'fa': 'Persian',
             'pl': 'Polish',
             'pt': 'Portuguese',
             'pa': 'Punjabi',
             'qu': 'Quechua',
             'ro': 'Romanian',
             'rm': 'Romansh',
             'rn': 'Rundi',
             'ru': 'Russian',
             'sg': 'Sango',
             'gd': 'Scottish Gaelic',
             'sr': 'Serbian',
             'sh': 'Serbo-Croatian',
             'sn': 'Shona',
             'ii': 'Sichuan Yi',
             'si': 'Sinhala',
             'sk': 'Slovak',
             'sl': 'Slovenian',
             'so': 'Somali',
             'es': 'Spanish',
             'sw': 'Swahili',
             'sv': 'Swedish',
             'tl': 'Tagalog',
             'ta': 'Tamil',
             'te': 'Telugu',
             'th': 'Thai',
             'bo': 'Tibetan',
             'ti': 'Tigrinya',
             'to': 'Tongan',
             'tr': 'Turkish',
             'uk': 'Ukrainian',
             'ur': 'Urdu',
             'ug': 'Uyghur',
             'uz': 'Uzbek',
             'vi': 'Vietnamese',
             'cy': 'Welsh',
             'fy': 'Western Frisian',
             'yi': 'Yiddish',
             'yo': 'Yoruba',
             'zu': 'Zulu'}

icu_codes_list = [{'code': 'af', 'name': 'Afrikaans'},
                  {'code': 'ak', 'name': 'Akan'},
                  {'code': 'sq', 'name': 'Albanian'},
                  {'code': 'am', 'name': 'Amharic'},
                  {'code': 'ar', 'name': 'Arabic'},
                  {'code': 'hy', 'name': 'Armenian'},
                  {'code': 'as', 'name': 'Assamese'},
                  {'code': 'az', 'name': 'Azerbaijani'},
                  {'code': 'bm', 'name': 'Bambara'},
                  {'code': 'eu', 'name': 'Basque'},
                  {'code': 'be', 'name': 'Belarusian'},
                  {'code': 'bn', 'name': 'Bengali'},
                  {'code': 'bs', 'name': 'Bosnian'},
                  {'code': 'br', 'name': 'Breton'},
                  {'code': 'bg', 'name': 'Bulgarian'},
                  {'code': 'my', 'name': 'Burmese'},
                  {'code': 'ca', 'name': 'Catalan'},
                  {'code': 'zh', 'name': 'Chinese'},
                  {'code': 'kw', 'name': 'Cornish'},
                  {'code': 'hr', 'name': 'Croatian'},
                  {'code': 'cs', 'name': 'Czech'},
                  {'code': 'da', 'name': 'Danish'},
                  {'code': 'nl', 'name': 'Dutch'},
                  {'code': 'dz', 'name': 'Dzongkha'},
                  {'code': 'en', 'name': 'English'},
                  {'code': 'eo', 'name': 'Esperanto'},
                  {'code': 'et', 'name': 'Estonian'},
                  {'code': 'ee', 'name': 'Ewe'},
                  {'code': 'fo', 'name': 'Faroese'},
                  {'code': 'fi', 'name': 'Finnish'},
                  {'code': 'fr', 'name': 'French'},
                  {'code': 'ff', 'name': 'Fulah'},
                  {'code': 'gl', 'name': 'Galician'},
                  {'code': 'lg', 'name': 'Ganda'},
                  {'code': 'ka', 'name': 'Georgian'},
                  {'code': 'de', 'name': 'German'},
                  {'code': 'el', 'name': 'Greek'},
                  {'code': 'gu', 'name': 'Gujarati'},
                  {'code': 'ha', 'name': 'Hausa'},
                  {'code': 'he', 'name': 'Hebrew'},
                  {'code': 'hi', 'name': 'Hindi'},
                  {'code': 'hu', 'name': 'Hungarian'},
                  {'code': 'is', 'name': 'Icelandic'},
                  {'code': 'ig', 'name': 'Igbo'},
                  {'code': 'id', 'name': 'Indonesian'},
                  {'code': 'ga', 'name': 'Irish'},
                  {'code': 'it', 'name': 'Italian'},
                  {'code': 'ja', 'name': 'Japanese'},
                  {'code': 'kl', 'name': 'Kalaallisut'},
                  {'code': 'kn', 'name': 'Kannada'},
                  {'code': 'ks', 'name': 'Kashmiri'},
                  {'code': 'kk', 'name': 'Kazakh'},
                  {'code': 'km', 'name': 'Khmer'},
                  {'code': 'ki', 'name': 'Kikuyu'},
                  {'code': 'rw', 'name': 'Kinyarwanda'},
                  {'code': 'ko', 'name': 'Korean'},
                  {'code': 'ky', 'name': 'Kyrgyz'},
                  {'code': 'lo', 'name': 'Lao'},
                  {'code': 'lv', 'name': 'Latvian'},
                  {'code': 'ln', 'name': 'Lingala'},
                  {'code': 'lt', 'name': 'Lithuanian'},
                  {'code': 'lu', 'name': 'Luba-Katanga'},
                  {'code': 'lb', 'name': 'Luxembourgish'},
                  {'code': 'mk', 'name': 'Macedonian'},
                  {'code': 'mg', 'name': 'Malagasy'},
                  {'code': 'ms', 'name': 'Malay'},
                  {'code': 'ml', 'name': 'Malayalam'},
                  {'code': 'mt', 'name': 'Maltese'},
                  {'code': 'gv', 'name': 'Manx'},
                  {'code': 'mr', 'name': 'Marathi'},
                  {'code': 'mn', 'name': 'Mongolian'},
                  {'code': 'ne', 'name': 'Nepali'},
                  {'code': 'nd', 'name': 'North Ndebele'},
                  {'code': 'se', 'name': 'Northern Sami'},
                  {'code': 'no', 'name': 'Norwegian'},
                  {'code': 'nb', 'name': 'Norwegian Bokmål'},
                  {'code': 'nn', 'name': 'Norwegian Nynorsk'},
                  {'code': 'or', 'name': 'Oriya'},
                  {'code': 'om', 'name': 'Oromo'},
                  {'code': 'os', 'name': 'Ossetic'},
                  {'code': 'ps', 'name': 'Pashto'},
                  {'code': 'fa', 'name': 'Persian'},
                  {'code': 'pl', 'name': 'Polish'},
                  {'code': 'pt', 'name': 'Portuguese'},
                  {'code': 'pa', 'name': 'Punjabi'},
                  {'code': 'qu', 'name': 'Quechua'},
                  {'code': 'ro', 'name': 'Romanian'},
                  {'code': 'rm', 'name': 'Romansh'},
                  {'code': 'rn', 'name': 'Rundi'},
                  {'code': 'ru', 'name': 'Russian'},
                  {'code': 'sg', 'name': 'Sango'},
                  {'code': 'gd', 'name': 'Scottish Gaelic'},
                  {'code': 'sr', 'name': 'Serbian'},
                  {'code': 'sh', 'name': 'Serbo-Croatian'},
                  {'code': 'sn', 'name': 'Shona'},
                  {'code': 'ii', 'name': 'Sichuan Yi'},
                  {'code': 'si', 'name': 'Sinhala'},
                  {'code': 'sk', 'name': 'Slovak'},
                  {'code': 'sl', 'name': 'Slovenian'},
                  {'code': 'so', 'name': 'Somali'},
                  {'code': 'es', 'name': 'Spanish'},
                  {'code': 'sw', 'name': 'Swahili'},
                  {'code': 'sv', 'name': 'Swedish'},
                  {'code': 'tl', 'name': 'Tagalog'},
                  {'code': 'ta', 'name': 'Tamil'},
                  {'code': 'te', 'name': 'Telugu'},
                  {'code': 'th', 'name': 'Thai'},
                  {'code': 'bo', 'name': 'Tibetan'},
                  {'code': 'ti', 'name': 'Tigrinya'},
                  {'code': 'to', 'name': 'Tongan'},
                  {'code': 'tr', 'name': 'Turkish'},
                  {'code': 'uk', 'name': 'Ukrainian'},
                  {'code': 'ur', 'name': 'Urdu'},
                  {'code': 'ug', 'name': 'Uyghur'},
                  {'code': 'uz', 'name': 'Uzbek'},
                  {'code': 'vi', 'name': 'Vietnamese'},
                  {'code': 'cy', 'name': 'Welsh'},
                  {'code': 'fy', 'name': 'Western Frisian'},
                  {'code': 'yi', 'name': 'Yiddish'},
                  {'code': 'yo', 'name': 'Yoruba'},
                  {'code': 'zu', 'name': 'Zulu'}]
