icu_codes = {'af': 'Afrikaans',
             'ak': 'Akan',
             'sq': 'Albanian',
             'am': 'Amharic',
             'ar': 'Arabic',
             'hy': 'Armenian',
             'as': 'Assamese',
             'az': 'Azerbaijani',
             'ay': 'Aymara ',
             'bm': 'Bambara',
             'eu': 'Basque',
             'be': 'Belarusian',
             'bn': 'Bengali',
             'bs': 'Bosnian',
             'br': 'Breton',
             'bg': 'Bulgarian',
             'my': 'Burmese',
             'ca': 'Catalan',
             'zh_Hans': 'Chinese (Simplified)',
             'zh_Hant': 'Chinese (Traditional)',
             'kw': 'Cornish',
             'hr': 'Croatian',
             'cs': 'Czech',
             'da': 'Danish',
             'nl': 'Dutch',
             'dz': 'Dzongkha',
             'en': 'English',
             'eo': 'Esperanto',
             'et': 'Estonian',
             'ee': 'Ewe',
             'fo': 'Faroese',
             'fi': 'Finnish',
             'fr': 'French',
             'ff': 'Fulah',
             'gl': 'Galician',
             'lg': 'Ganda',
             'ka': 'Georgian',
             'de': 'German',
             'el': 'Greek',
             'gu': 'Gujarati',
             'ha': 'Hausa',
             'he': 'Hebrew',
             'hi': 'Hindi',
             'hu': 'Hungarian',
             'is': 'Icelandic',
             'ig': 'Igbo',
             'id': 'Indonesian',
             'ga': 'Irish',
             'it': 'Italian',
             'ja': 'Japanese',
             'kl': 'Kalaallisut',
             'kn': 'Kannada',
             'ks': 'Kashmiri',
             'kk': 'Kazakh',
             'xnz': 'Kenzi (Nubian)',
             'km': 'Khmer',
             'ki': 'Kikuyu',
             'rw': 'Kinyarwanda',
             'ku': 'Kurdish',
             'ko': 'Korean',
             'ky': 'Kyrgyz',
             'lo': 'Lao',
             'lv': 'Latvian',
             'ln': 'Lingala',
             'lt': 'Lithuanian',
             'lu': 'Luba-Katanga',
             'lb': 'Luxembourgish',
             'mk': 'Macedonian',
             'mg': 'Malagasy',
             'ms': 'Malay',
             'ml': 'Malayalam',
             'mt': 'Maltese',
             'gv': 'Manx',
             'mr': 'Marathi',
             'mn': 'Mongolian',
             'ne': 'Nepali',
             'nd': 'North Ndebele',
             'se': 'Northern Sami',
             'no': 'Norwegian',
             'nb': 'Norwegian Bokmål',
             'nn': 'Norwegian Nynorsk',
             'or': 'Oriya',
             'om': 'Oromo',
             'os': 'Ossetic',
             'ps': 'Pashto',
             'fa': 'Persian',
             'pl': 'Polish',
             'pt': 'Portuguese',
             'pa': 'Punjabi',
             'qu': 'Quechua',
             'ro': 'Romanian',
             'rm': 'Romansh',
             'rn': 'Rundi',
             'ru': 'Russian',
             'sg': 'Sango',
             'sat': 'Santali',
             'gd': 'Scottish Gaelic',
             'sr': 'Serbian',
             'sh': 'Serbo-Croatian',
             'sn': 'Shona',
             'ii': 'Sichuan Yi',
             'si': 'Sinhala',
             'sk': 'Slovak',
             'sl': 'Slovenian',
             'so': 'Somali',
             'es': 'Spanish',
             'sw': 'Swahili',
             'sv': 'Swedish',
             'tl': 'Tagalog',
             'ta': 'Tamil',
             'te': 'Telugu',
             'tdt': 'Tetum',
             'th': 'Thai',
             'bo': 'Tibetan',
             'ti': 'Tigrinya',
             'to': 'Tongan',
             'tr': 'Turkish',
             'uk': 'Ukrainian',
             'ur': 'Urdu',
             'ug': 'Uyghur',
             'uz': 'Uzbek',
             'vi': 'Vietnamese',
             'cy': 'Welsh',
             'fy': 'Western Frisian',
             'yi': 'Yiddish',
             'yo': 'Yoruba',
             'zu': 'Zulu'}

icu_codes_list = [{'code': 'af', 'name': 'Afrikaans'},
                  {'code': 'ak', 'name': 'Akan'},
                  {'code': 'sq', 'name': 'Albanian'},
                  {'code': 'am', 'name': 'Amharic'},
                  {'code': 'ar', 'name': 'Arabic'},
                  {'code': 'hy', 'name': 'Armenian'},
                  {'code': 'as', 'name': 'Assamese'},
                  {'code': 'az', 'name': 'Azerbaijani'},
                  {'code': 'ay', 'name': 'Aymara '},
                  {'code': 'bm', 'name': 'Bambara'},
                  {'code': 'eu', 'name': 'Basque'},
                  {'code': 'be', 'name': 'Belarusian'},
                  {'code': 'bn', 'name': 'Bengali'},
                  {'code': 'bs', 'name': 'Bosnian'},
                  {'code': 'br', 'name': 'Breton'},
                  {'code': 'bg', 'name': 'Bulgarian'},
                  {'code': 'my', 'name': 'Burmese'},
                  {'code': 'ca', 'name': 'Catalan'},
                  {'code': 'zh_Hans', 'name': 'Chinese (Simplified)'},
                  {'code': 'zh_Hant', 'name': 'Chinese (Traditional)'},
                  {'code': 'kw', 'name': 'Cornish'},
                  {'code': 'hr', 'name': 'Croatian'},
                  {'code': 'cs', 'name': 'Czech'},
                  {'code': 'da', 'name': 'Danish'},
                  {'code': 'nl', 'name': 'Dutch'},
                  {'code': 'dz', 'name': 'Dzongkha'},
                  {'code': 'en', 'name': 'English'},
                  {'code': 'eo', 'name': 'Esperanto'},
                  {'code': 'et', 'name': 'Estonian'},
                  {'code': 'ee', 'name': 'Ewe'},
                  {'code': 'fo', 'name': 'Faroese'},
                  {'code': 'fi', 'name': 'Finnish'},
                  {'code': 'fr', 'name': 'French'},
                  {'code': 'ff', 'name': 'Fulah'},
                  {'code': 'gl', 'name': 'Galician'},
                  {'code': 'lg', 'name': 'Ganda'},
                  {'code': 'ka', 'name': 'Georgian'},
                  {'code': 'de', 'name': 'German'},
                  {'code': 'el', 'name': 'Greek'},
                  {'code': 'gu', 'name': 'Gujarati'},
                  {'code': 'ha', 'name': 'Hausa'},
                  {'code': 'he', 'name': 'Hebrew'},
                  {'code': 'hi', 'name': 'Hindi'},
                  {'code': 'hu', 'name': 'Hungarian'},
                  {'code': 'is', 'name': 'Icelandic'},
                  {'code': 'ig', 'name': 'Igbo'},
                  {'code': 'id', 'name': 'Indonesian'},
                  {'code': 'ga', 'name': 'Irish'},
                  {'code': 'it', 'name': 'Italian'},
                  {'code': 'ja', 'name': 'Japanese'},
                  {'code': 'kl', 'name': 'Kalaallisut'},
                  {'code': 'kn', 'name': 'Kannada'},
                  {'code': 'ks', 'name': 'Kashmiri'},
                  {'code': 'kk', 'name': 'Kazakh'},
                  {'code': 'xnz', 'name': 'Kenzi (Nubian)'},
                  {'code': 'km', 'name': 'Khmer'},
                  {'code': 'ki', 'name': 'Kikuyu'},
                  {'code': 'rw', 'name': 'Kinyarwanda'},
                  {'code': 'ko', 'name': 'Korean'},
                  {'code': 'ku', 'name': 'Kurdish'},
                  {'code': 'ky', 'name': 'Kyrgyz'},
                  {'code': 'lo', 'name': 'Lao'},
                  {'code': 'lv', 'name': 'Latvian'},
                  {'code': 'ln', 'name': 'Lingala'},
                  {'code': 'lt', 'name': 'Lithuanian'},
                  {'code': 'lu', 'name': 'Luba-Katanga'},
                  {'code': 'lb', 'name': 'Luxembourgish'},
                  {'code': 'mk', 'name': 'Macedonian'},
                  {'code': 'mg', 'name': 'Malagasy'},
                  {'code': 'ms', 'name': 'Malay'},
                  {'code': 'ml', 'name': 'Malayalam'},
                  {'code': 'mt', 'name': 'Maltese'},
                  {'code': 'gv', 'name': 'Manx'},
                  {'code': 'mr', 'name': 'Marathi'},
                  {'code': 'mn', 'name': 'Mongolian'},
                  {'code': 'ne', 'name': 'Nepali'},
                  {'code': 'nd', 'name': 'North Ndebele'},
                  {'code': 'se', 'name': 'Northern Sami'},
                  {'code': 'no', 'name': 'Norwegian'},
                  {'code': 'nb', 'name': 'Norwegian Bokmål'},
                  {'code': 'nn', 'name': 'Norwegian Nynorsk'},
                  {'code': 'or', 'name': 'Oriya'},
                  {'code': 'om', 'name': 'Oromo'},
                  {'code': 'os', 'name': 'Ossetic'},
                  {'code': 'ps', 'name': 'Pashto'},
                  {'code': 'fa', 'name': 'Persian'},
                  {'code': 'pl', 'name': 'Polish'},
                  {'code': 'pt', 'name': 'Portuguese'},
                  {'code': 'pa', 'name': 'Punjabi'},
                  {'code': 'qu', 'name': 'Quechua'},
                  {'code': 'ro', 'name': 'Romanian'},
                  {'code': 'rm', 'name': 'Romansh'},
                  {'code': 'rn', 'name': 'Rundi'},
                  {'code': 'ru', 'name': 'Russian'},
                  {'code': 'sg', 'name': 'Sango'},
                  {'code': 'sat', 'name': 'Santali'},
                  {'code': 'gd', 'name': 'Scottish Gaelic'},
                  {'code': 'sr', 'name': 'Serbian'},
                  {'code': 'sh', 'name': 'Serbo-Croatian'},
                  {'code': 'sn', 'name': 'Shona'},
                  {'code': 'ii', 'name': 'Sichuan Yi'},
                  {'code': 'si', 'name': 'Sinhala'},
                  {'code': 'sk', 'name': 'Slovak'},
                  {'code': 'sl', 'name': 'Slovenian'},
                  {'code': 'so', 'name': 'Somali'},
                  {'code': 'es', 'name': 'Spanish'},
                  {'code': 'sw', 'name': 'Swahili'},
                  {'code': 'sv', 'name': 'Swedish'},
                  {'code': 'tl', 'name': 'Tagalog'},
                  {'code': 'ta', 'name': 'Tamil'},
                  {'code': 'te', 'name': 'Telugu'},
                  {'code': 'tdt', 'name': 'Tetum'},
                  {'code': 'th', 'name': 'Thai'},
                  {'code': 'bo', 'name': 'Tibetan'},
                  {'code': 'ti', 'name': 'Tigrinya'},
                  {'code': 'to', 'name': 'Tongan'},
                  {'code': 'tr', 'name': 'Turkish'},
                  {'code': 'uk', 'name': 'Ukrainian'},
                  {'code': 'ur', 'name': 'Urdu'},
                  {'code': 'ug', 'name': 'Uyghur'},
                  {'code': 'uz', 'name': 'Uzbek'},
                  {'code': 'vi', 'name': 'Vietnamese'},
                  {'code': 'cy', 'name': 'Welsh'},
                  {'code': 'fy', 'name': 'Western Frisian'},
                  {'code': 'yi', 'name': 'Yiddish'},
                  {'code': 'yo', 'name': 'Yoruba'},
                  {'code': 'zu', 'name': 'Zulu'}]

icu_codes_list_tuples = [(key, val) for key, val in icu_codes.items()]

programming_languages = {'apl': 'APL',
                         'assembly': 'Assembly',
                         'bash_shell': 'Bash/Shell',
                         'c': 'C',
                         'c_sharp': 'C#',
                         'c_plusplus': 'C++',
                         'cobol': 'COBOL',
                         'clojure': 'Clojure',
                         'crystal': 'Crystal',
                         'dart': 'Dart',
                         'delphi': 'Delphi',
                         'elixir': 'Elixir',
                         'erlang': 'Erlang',
                         'f_sharp': 'F#',
                         'golang': 'Go',
                         'groovy': 'Groovy',
                         'haskell': 'Haskell',
                         'java': 'Java',
                         'javascript': 'JavaScript',
                         'julia': 'Julia',
                         'kotlin': 'Kotlin',
                         'lisp': 'LISP',
                         'matlab': 'Matlab',
                         'node_js': 'Node.js',
                         'objective_c': 'Objective-C',
                         'php': 'PHP',
                         'perl': 'Perl',
                         'powershell': 'PowerShell',
                         'python': 'Python',
                         'r': 'R',
                         'ruby': 'Ruby',
                         'rust': 'Rust',
                         'sql': 'SQL',
                         'scala': 'Scala',
                         'swift': 'Swift',
                         'stata': 'Stata Script (Ado)',
                         'typescript': 'TypeScript',
                         'vba': 'VBA'}

licenses = {'proprietary': 'Proprietary (any kind of non-free EULA)',
            'afl-3.0': 'Academic Free License v3.0', 
            'apache-2.0': 'Apache license 2.0', 
            'artistic-2.0': 'Artistic license 2.0', 
            'bsl-1.0': 'Boost Software License 1.0', 
            'bsd-2-clause': 'BSD 2-clause "Simplified" license', 
            'bsd-3-clause': 'BSD 3-clause "New" or "Revised" license', 
            'bsd-3-clause-clear': 'BSD 3-clause Clear license', 
            'cc': 'Creative Commons license family', 
            'cc0-1.0': 'Creative Commons Zero v1.0 Universal', 
            'cc-by-4.0': 'Creative Commons Attribution 4.0', 
            'cc-by-sa-4.0': 'Creative Commons Attribution Share Alike 4.0', 
            'wtfpl': 'Do What The F*ck You Want To Public License', 
            'ecl-2.0': 'Educational Community License v2.0', 
            'epl-1.0': 'Eclipse Public License 1.0', 
            'epl-2.0': 'Eclipse Public License 2.0', 
            'eupl-1.1': 'European Union Public License 1.1', 
            'agpl-3.0': 'GNU Affero General Public License v3.0', 
            'gpl': 'GNU General Public License family', 
            'gpl-2.0': 'GNU General Public License v2.0', 
            'gpl-3.0': 'GNU General Public License v3.0', 
            'lgpl': 'GNU Lesser General Public License family', 
            'lgpl-2.1': 'GNU Lesser General Public License v2.1', 
            'lgpl-3.0': 'GNU Lesser General Public License v3.0', 
            'isc': 'ISC', 
            'lppl-1.3c': 'LaTeX Project Public License v1.3c', 
            'ms-pl': 'Microsoft Public License', 
            'mit': 'MIT', 
            'mpl-2.0': 'Mozilla Public License 2.0', 
            'osl-3.0': 'Open Software License 3.0', 
            'postgresql': 'PostgreSQL License', 
            'ofl-1.1': 'SIL Open Font License 1.1', 
            'ncsa': 'University of Illinois/NCSA Open Source License', 
            'unlicense': 'The Unlicense', 
            'zlib': 'zLib License',
            'na': 'NA (license not specified)'
    }